### ISSUE TITLE
Versioning on Github and Rubygems do not match, cannot install some versions

### ISSUE THREAD

**Issue by rcamps** [merge-api/merge-ruby-client#21]
Versions on Github: 0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.0.5

Versions on Rubygems: 0.0.1, 0.0.3, 0.1.0

**Comment by rcamps** [comment]
<img width="1016" alt="Screenshot 2024-05-23 at 2 51 10 PM" src="https://github.com/merge-api/merge-ruby-client/assets/25013996/3911a0c7-5856-492e-a6b0-1d71e0c80b2b">

**Comment by armandobelardo** [comment]
Hi there @rcamps thank you for flagging this! It looks like our versioning got out of sync, we should be back now and you should be able to pull the latest version at 0.1.1!

Closing this out now, but feel free to reopen if you encounter any issues
